files:
  - 
    source: /k9mail/src/main/res/values/strings.xml
    translation: '/k9mail/src/main/res/values-%two_letters_code%/strings.xml'
    languages_mapping:
      two_letters_code:
        zh-CN: zh-rCN
  - 
    source: '/**/*.md'
    translation: '/%original_path%/%file_name%(%locale%).md'
